# Generated by Django 4.2.2 on 2023-07-14 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name': 'Friend', 'verbose_name_plural': 'Friends'},
        ),
        migrations.AddField(
            model_name='friends',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='friends',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_unused_friend_relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friends',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('from_user', 'to_user')},
        ),
    ]
