# Generated by Django 4.2.2 on 2023-07-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_friendsrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendsrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendsrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendsrequest',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='FriendsRequest',
        ),
    ]
